name: Auto Login

on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches:
      - main
      
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'

jobs:
  login:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.42.0-jammy
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Fix for running in container
      - name: Setup user for browser
        run: |
          # Create a new user to run the browser
          groupadd -r pwuser && useradd -r -g pwuser -G audio,video pwuser
          mkdir -p /home/pwuser
          chown -R pwuser:pwuser /home/pwuser
          # Make the project directory accessible to pwuser
          chown -R pwuser:pwuser .
          
      - name: Run login script
        run: |
          # Run as non-root user
          su pwuser -c 'python login_script.py'
        timeout-minutes: 20
        
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: login-script-logs
          path: |
            *.log
            *.txt
          retention-days: 3
