name: Auto Login

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  # Allow manual triggers
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 \
          libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 \
          libgbm1 libpango-1.0-0 libcairo2 libasound2 libatspi2.0-0 libx11-xcb1 \
          libffi8 libx264-155
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright==1.42.0
        playwright install --with-deps chromium
        
    - name: Run login script
      run: |
        python login_script.py
      timeout-minutes: 20
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: login-script-logs
        path: |
          *.log
          *.txt
        retention-days: 3
