name: Auto Login

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  # Allow manual triggers
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.0-jammy
      options: --ipc=host --shm-size=2gb
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install playwright==1.42.0
        
    - name: Run login script
      run: |
        # Run the login script with a 20-minute timeout (1200 seconds)
        timeout 1200 python3 login_script.py
        
        # Check if the script ran successfully
        if [ $? -eq 124 ]; then
          echo "Script timed out after 20 minutes"
          exit 1
        fi
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: login-script-logs
        path: |
          *.log
          *.txt
        retention-days: 3
