name: Auto Login

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  # Allow manual triggers
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright==1.42.0
        playwright install
        playwright install-deps
        
    - name: Run login script
      run: |
        # Set display for headful mode
        export DISPLAY=:99
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x1024x24 -ac +extension GLX +render -noreset
        
        # Run the login script with a 10-minute timeout (600 seconds)
        timeout 1200 python login_script.py
        
        # Check if the script ran successfully
        if [ $? -eq 124 ]; then
          echo "Script timed out after 20 minutes"
          exit 1
        fi
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: login-script-logs
        path: |
          *.log
          *.txt
        retention-days: 3
