name: Auto Login

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  # Allow manual triggers
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright==1.42.0
        
    - name: Install Playwright browsers
      run: |
        playwright install --with-deps chromium
        
    - name: Run login script
      run: |
        # Run the login script with a 20-minute timeout (1200 seconds)
        timeout 1200 python login_script.py
        
        # Check if the script ran successfully
        if [ $? -eq 124 ]; then
          echo "Script timed out after 20 minutes"
          exit 1
        fi
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: login-script-logs
        path: |
          *.log
          *.txt
        retention-days: 3
