name: Keep Streamlit App Alive and Auto-Predict

on:
  schedule:
    - cron: '0 */5 * * *'  # Runs every 5 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run auto-prediction
        run: |
          python auto_predict.py

      - name: Health check
        if: always()  # Run even if auto-prediction fails
        run: |
          # Function to check if the app is accessible
          check_app() {
            response=$(curl -s -o /dev/null -w "%{http_code}" "https://fottyygit.streamlit.app")
            if [ "$response" = "200" ] || [ "$response" = "303" ]; then
              return 0
            else
              return 1
            fi
          }
          
          # Try up to 3 times
          for i in {1..3}; do
            echo "Attempt $i: Checking app health..."
            if check_app; then
              echo "Health check successful - app is accessible!"
              exit 0
            else
              if [ $i -lt 3 ]; then
                echo "Health check failed, retrying in 10 seconds..."
                sleep 10
              else
                echo "Health check failed after 3 attempts"
                exit 1
              fi
            fi
          done
              else
                echo "Health check failed after 3 attempts"
                echo "Response: $HEALTH_CHECK"
                exit 1
              fi
            fi
          done
          
          # Clean up
          rm -f cookies.txt
        continue-on-error: true
