name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */5 * * *'  # Runs every 5 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Keep app alive
        run: |
          python auto_predict.py
        continue-on-error: true  # Continue even if script fails

      - name: Health check
        if: always()  # Run even if keep-alive fails
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" "https://fottyygit.streamlit.app/?page=login")
          if [ "$response" = "200" ] || [ "$response" = "303" ]; then
            echo "Health check successful - app is accessible!"
            exit 0
          else
            echo "Health check failed - app returned status $response"
            exit 1
          fi
