name: Keep Streamlit App Alive and Auto-Predict

on:
  schedule:
    - cron: '0 */10 * * *'  # Runs every 10 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run auto-prediction
        run: |
          python auto_predict.py

      - name: Health check
        if: always()  # Run even if auto-prediction fails
        run: |
          # First get initial session and handle auth redirect
          RESPONSE=$(curl -s -c cookies.txt -L "https://fottyy.streamlit.app")
          
          # Login with form data and follow redirects
          curl -s -b cookies.txt -c cookies.txt -L -X POST "https://fottyy.streamlit.app/?page=login" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=matchday_wizard&password=GoalMaster"
          
          # Now use the authenticated session for health check
          for i in {1..3}; do
            echo "Attempt $i: Checking app health..."
            HEALTH_CHECK=$(curl -s -b cookies.txt -L "https://fottyy.streamlit.app/?health-check=true")
            
            if echo "$HEALTH_CHECK" | grep -q '"status": "healthy"'; then
              echo "Health check successful!"
              break
            else
              if [ $i -lt 3 ]; then
                echo "Health check failed, retrying in 10 seconds..."
                sleep 10
              else
                echo "Health check failed after 3 attempts"
                echo "Response: $HEALTH_CHECK"
                exit 1
              fi
            fi
          done
          
          # Clean up
          rm -f cookies.txt
        continue-on-error: true
