[server]
enableXsrfProtection = true
enableCORS = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
# Modern color scheme
primaryColor = "#3b82f6"  # Bright blue
backgroundColor = "#ffffff"  # Pure white
secondaryBackgroundColor = "#f8fafc"  # Light gray
textColor = "#1e293b"  # Dark slate
font = "sans serif"

# Additional theme customization
base = "light"
secondaryColor = "#38bdf8"  # Light blue for secondary elements
tertiaryColor = "#818cf8"   # Purple for tertiary elements

[ui]
hideSidebarNav = true
animation = true
transition = 1000

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"
formatters = "simple"

[client]
toolbarMode = "minimal"
showErrorDetails = false
caching = true

[runner]
fastReruns = true
enforceSerializableSessionState = false

[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false

[mapbox]
token = ""  # Add your mapbox token if using maps

[global]
developmentMode = false
disableWatchdogWarning = true
suppressDeprecationWarnings = true

[server.fileWatcherType]
type = "auto"

[browser.serverSentEvents]
enabled = true

[theme.components]
# Custom styling for specific components
stButton = "#3b82f6"  # Primary button color
stProgress = "#10b981"  # Progress bar color
stSuccess = "#34d399"  # Success message color
stError = "#ef4444"  # Error message color
stWarning = "#f59e0b"  # Warning message color
stInfo = "#3b82f6"  # Info message color

[theme.font]
# Font settings
sansSerif = "Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif"
monospace = "Source Code Pro, Consolas, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace"
sizeSmall = "12px"
sizeMedium = "14px"
sizeLarge = "16px"
